import { Question } from '@/types/form'

export const questions: Question[] = [
  {
    id: 'P1',
    notionField: 'nome',
    type: 'text',
    question: 'Qual é o seu nome?',
    placeholder: 'Seu primeiro nome está ótimo :)',
    required: true,
  },
  {
    id: 'P2',
    notionField: 'whatsapp',
    type: 'tel',
    question: 'WhatsApp pra gente se falar:',
    placeholder: '(00) 00000-0000',
    required: true,
  },
  {
    id: 'P3',
    notionField: 'email',
    type: 'email',
    question: 'Seu melhor e-mail:',
    placeholder: 'email@exemplo.com',
    sublabel: 'Só pra garantir que você recebe meu contato, ok?',
    required: true,
  },
  {
    id: 'P4',
    notionField: 'empresa',
    type: 'text',
    question: 'Nome da empresa ou projeto:',
    placeholder: 'Como o mundo conhece o seu negócio',
    required: true,
  },
  {
    id: 'P5',
    notionField: 'instagram',
    type: 'text',
    question: 'Instagram da empresa ou projeto:',
    placeholder: '@',
    sublabel: 'Se tiver — me ajuda a entender sua marca antes da conversa.',
    required: false,
  },
  {
    id: 'P6',
    notionField: 'perfil',
    type: 'single-choice',
    question: 'Como você se descreve melhor?',
    required: true,
    autoAdvance: true,
    options: [
      { id: 'A', label: 'Sou fundador(a) ou dono(a) do negócio e quero construir ou fortalecer minha marca.' },
      { id: 'B', label: 'Estou lançando um negócio ou ideia e preciso estruturar minha marca do zero.' },
      { id: 'C', label: 'Sou gestor(a) em uma empresa e tenho autonomia para contratar serviços de marca.' },
      { id: 'D', label: 'Outro...' },
    ],
  },
  {
    id: 'P7',
    notionField: 'segmento',
    type: 'single-choice',
    question: 'Em qual segmento o negócio atua?',
    required: true,
    autoAdvance: true,
    options: [
      { id: 'A', label: 'Moda e Beleza' },
      { id: 'B', label: 'Alimentação e Bebidas' },
      { id: 'C', label: 'Saúde e Bem-estar' },
      { id: 'D', label: 'Educação e Consultoria' },
      { id: 'E', label: 'Tecnologia e Inovação' },
      { id: 'F', label: 'Arquitetura, Design e Decoração' },
      { id: 'G', label: 'Entretenimento e Cultura' },
      { id: 'H', label: 'Varejo e Comércio' },
      { id: 'I', label: 'Serviços Corporativos e Profissionais' },
      { id: 'J', label: 'Outro...' },
    ],
  },
  {
    id: 'P8',
    notionField: 'momento',
    type: 'single-choice',
    question: 'Qual é o momento atual do negócio?',
    required: true,
    autoAdvance: false,
    options: [
      {
        id: 'A',
        label: 'Estou estruturando ou reposicionando minha marca para que ela tenha uma identidade clara e se conecte melhor com meu público.',
        sublabel: '🔴 Tipo o Nubank no início',
      },
      {
        id: 'B',
        label: 'Estou crescendo e quero que minha marca transmita mais valor e credibilidade para conquistar mais clientes.',
        sublabel: '🔴 Sabe a Dengo Chocolates?',
      },
      {
        id: 'C',
        label: 'Minha marca já tem presença ou é conhecida, mas preciso modernizá-la e adaptá-la ao mercado atual.',
        sublabel: '🔴 Como a Havaianas',
      },
      {
        id: 'D',
        label: 'Quero criar uma experiência marcante para um evento, espaço, embalagem ou serviço.',
        sublabel: '🔴 Tipo a Granado',
      },
    ],
  },
  {
    id: 'P9',
    notionField: 'desafios',
    type: 'multi-choice',
    question: 'O que você sente que falta na sua marca hoje?',
    sublabel: 'Marque tudo que fizer sentido.',
    required: true,
    options: [
      { id: 'A', label: 'Não tenho clareza sobre o propósito, posicionamento ou diferencial da minha marca' },
      { id: 'B', label: 'Minha marca não se destaca nem se diferencia dos concorrentes' },
      { id: 'C', label: 'Tenho dificuldade de atrair o público certo e comunicar meu valor' },
      { id: 'D', label: 'Minha identidade visual não transmite a essência e o nível da minha marca' },
      { id: 'E', label: 'Não consigo cobrar mais porque minha marca não transmite credibilidade suficiente' },
      { id: 'F', label: 'Minha marca é inconsistente — muda de cara dependendo do canal ou material' },
      { id: 'G', label: 'Tenho a marca, mas não sei como ativá-la e aplicá-la de forma estratégica' },
      { id: 'H', label: 'Não tenho uma estratégia clara de como evoluir minha marca ao longo do tempo' },
    ],
  },
  {
    id: 'P10',
    notionField: 'estagio_marca',
    type: 'single-choice',
    question: 'Qual dessas opções melhor descreve o estágio atual da sua marca?',
    required: true,
    autoAdvance: true,
    options: [
      { id: 'A', label: 'Ainda não comecei — tenho a ideia mas a marca não existe ainda' },
      { id: 'B', label: 'Tenho uma identidade visual mas não tenho estratégia nem posicionamento definido' },
      { id: 'C', label: 'Tenho a estratégia e a identidade, mas falta consistência e aplicação nos canais' },
      { id: 'D', label: 'Tenho uma marca estruturada, mas precisa evoluir ou ser reposicionada' },
    ],
  },
  {
    id: 'P11',
    notionField: 'disponibilidade',
    type: 'single-choice',
    question: 'Como está sua disponibilidade para participar do projeto?',
    sublabel: 'Projetos de marca têm mais resultado quando o cliente participa ativamente. Quero entender como funciona melhor pra você.',
    required: true,
    autoAdvance: true,
    options: [
      { id: 'A', label: 'Consigo participar ativamente — entendo que o resultado depende da minha presença' },
      { id: 'B', label: 'Tenho pouco tempo, mas consigo me envolver nos momentos-chave do projeto' },
      { id: 'C', label: 'Prefiro uma solução mais autônoma, com minha participação apenas no essencial' },
    ],
  },
  {
    id: 'P12',
    notionField: 'motivacao',
    type: 'textarea',
    question: 'Em uma frase: o que te fez chegar até aqui?',
    placeholder: 'Escreva com suas próprias palavras...',
    sublabel: 'Pode ser uma frustração, uma virada, um objetivo — o que quiser compartilhar.',
    required: true,
  },
]
